import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { MessageSquare, X, Send, Bot, User, Zap, Activity, Database, ShieldCheck } from 'lucide-react';

const ChatBot = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([
    { role: 'bot', content: "Hello! I'm GearBot, your GearGuide industrial assistant. How can I help you optimize your factory floor today?" }
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const scrollRef = useRef(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, isTyping]);

  const knowledgeBase = {
    greetings: ["hi", "hello", "hey", "greetings"],
    about: ["what is gearguide", "about", "who are you", "what do you do"],
    ai: ["agent", "superior ai", "prediction", "ai", "failure"],
    inventory: ["machine", "inventory", "assets", "hardware", "cnc", "lathe"],
    logs: ["logs", "maintenance", "tracking", "records", "dispatch"],
    pricing: ["price", "cost", "free", "plan"],
    setup: ["how to start", "register", "onboard", "setup"]
  };

  const getBotResponse = (userInput) => {
    const input = userInput.toLowerCase();
    
    if (knowledgeBase.greetings.some(word => input.includes(word))) {
      return "Hello! I'm here to help you explore GearGuide's predictive maintenance capabilities. Ask me about our AI, Inventory management, or Maintenance logs!";
    }
    
    if (knowledgeBase.about.some(word => input.includes(word))) {
      return "GearGuide is a state-of-the-art predictive maintenance platform. We help factories reduce downtime by predicting machine failures before they happen using neural networks.";
    }
    
    if (knowledgeBase.ai.some(word => input.includes(word))) {
      return "Our 'Superior AI Agent' uses deep learning to analyze machine telemetry in real-time. It can detect anomalies in vibration or temperature with 98% accuracy.";
    }
    
    if (knowledgeBase.inventory.some(word => input.includes(word))) {
      return "The 'Inventory Machine' section allows you to manage all factory assets. You can onboard CNC machines, industrial robots, and lathes to our secure cloud.";
    }
    
    if (knowledgeBase.logs.some(word => input.includes(word))) {
      return "Maintenance Logs are automatically generated by our AI. When a risk is detected, the system dispatches a digital work order to your technicians instantly.";
    }
    
    if (knowledgeBase.setup.some(word => input.includes(word))) {
      return "To get started, simply click the 'Register Company' button on the top right. Once verified, you can begin onboarding your machines!";
    }

    if (knowledgeBase.pricing.some(word => input.includes(word))) {
        return "GearGuide offers enterprise-grade solutions. Contact our sales team via the footer details for a custom quote tailored to your plant's scale.";
    }

    return "That's an interesting question! For specific technical queries about your hardware integration, it's best to check our documentation or contact support at onboard@gearguide.ai.";
  };

  const handleSend = () => {
    if (!input.trim()) return;

    const userMessage = { role: 'user', content: input };
    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsTyping(true);

    // Simulate bot thinking
    setTimeout(() => {
      const botResponse = { role: 'bot', content: getBotResponse(input) };
      setMessages(prev => [...prev, botResponse]);
      setIsTyping(false);
    }, 1000);
  };

  return (
    <div className="fixed bottom-20 right-8 z-[100]">
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 50, scale: 0.8 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 50, scale: 0.8 }}
            className="mb-6 w-[350px] md:w-[400px] h-[500px] bg-white rounded-[2.5rem] shadow-[0_30px_100px_rgba(0,0,0,0.2)] border border-gray-100 overflow-hidden flex flex-col"
          >
            {/* Header */}
            <div className="bg-[#0A1118] p-6 text-white flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center border border-blue-500/30">
                  <Bot size={24} className="text-blue-400" />
                </div>
                <div>
                  <h3 className="font-black text-sm tracking-tight">GearBot AI</h3>
                  <div className="flex items-center">
                    <span className="w-2 h-2 rounded-full bg-green-500 mr-2"></span>
                    <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Online Assistant</span>
                  </div>
                </div>
              </div>
              <button onClick={() => setIsOpen(false)} className="text-gray-400 hover:text-white transition-colors">
                <X size={20} />
              </button>
            </div>

            {/* Messages */}
            <div ref={scrollRef} className="flex-1 overflow-y-auto p-6 space-y-4 bg-gray-50/50">
              {messages.map((msg, i) => (
                <motion.div
                  initial={{ opacity: 0, x: msg.role === 'bot' ? -10 : 10 }}
                  animate={{ opacity: 1, x: 0 }}
                  key={i}
                  className={`flex ${msg.role === 'bot' ? 'justify-start' : 'justify-end'}`}
                >
                  <div className={`max-w-[80%] p-4 rounded-2xl text-sm font-medium ${
                    msg.role === 'bot' 
                    ? 'bg-white text-gray-800 shadow-sm border border-gray-100 rounded-tl-none' 
                    : 'bg-[#3B82F6] text-white shadow-md rounded-tr-none'
                  }`}>
                    {msg.content}
                  </div>
                </motion.div>
              ))}
              {isTyping && (
                <div className="flex justify-start">
                  <div className="bg-white p-4 rounded-2xl shadow-sm border border-gray-100 rounded-tl-none flex space-x-1">
                    <span className="w-1.5 h-1.5 bg-gray-300 rounded-full animate-bounce"></span>
                    <span className="w-1.5 h-1.5 bg-gray-300 rounded-full animate-bounce delay-100"></span>
                    <span className="w-1.5 h-1.5 bg-gray-300 rounded-full animate-bounce delay-200"></span>
                  </div>
                </div>
              )}
            </div>

            {/* Input */}
            <div className="p-4 bg-white border-t border-gray-100">
              <div className="relative">
                <input
                  type="text"
                  placeholder="Ask GearBot anything..."
                  className="w-full bg-gray-50 border border-gray-200 rounded-2xl px-5 py-3 pr-12 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all font-medium"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && handleSend()}
                />
                <button
                  onClick={handleSend}
                  className="absolute right-2 top-1.5 p-2 bg-[#0A1118] text-white rounded-xl hover:bg-blue-600 transition-colors shadow-lg"
                >
                  <Send size={16} />
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Toggle Button */}
      <motion.button
        whileHover={{ scale: 1.1 }}
        whileTap={{ scale: 0.9 }}
        onClick={() => setIsOpen(!isOpen)}
        className="w-16 h-16 bg-[#0A1118] text-white rounded-full shadow-[0_20px_60px_rgba(0,0,0,0.3)] flex items-center justify-center relative border border-white/10 group"
      >
        <span className="absolute -top-1 -right-1 w-5 h-5 bg-blue-500 rounded-full flex items-center justify-center border-2 border-[#0A1118] z-10">
           <span className="w-1.5 h-1.5 bg-white rounded-full animate-pulse"></span>
        </span>
        {isOpen ? <X size={28} /> : <MessageSquare size={28} />}
      </motion.button>
    </div>
  );
};

export default ChatBot;
